AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""

Parameters:
    Subnets:
        Type: "List<AWS::EC2::Subnet::Id>"
        Description: "Subnets to deploy Lambda into"
    SecurityGroup:
        Type: "AWS::EC2::SecurityGroup::Id"
        Description: "Security Group to deploy Lambda into"

Resources:
    LambdaFunction:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            Environment: 
                Variables: 
                    DB_PASS: "pl4nt5!"
                    DB_USER: "plantshop"
                    DB_HOST: !Sub "database-1-instance-1.cqkudy00onyy.${AWS::Region}.rds.amazonaws.com"
            FunctionName: "PlantShopAPI"
            Handler: "index.handler"
            Architectures: 
              - "x86_64"
            Code: 
                S3Bucket: "<bucket-name>"
                S3Key: "lambda.zip"
            MemorySize: 128
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/PlantShopAPI-role-atj2dtq2"
            Runtime: "nodejs16.x"
            Timeout: 3
            TracingConfig: 
                Mode: "PassThrough"
            VpcConfig: 
                SubnetIds:
                  - !Ref Subnets 
                SecurityGroupIds: 
                  - !Ref SecurityGroup
            EphemeralStorage: 
                Size: 512

    LambdaUrl:
        Type: "AWS::Lambda::Url"
        Properties:
            TargetFunctionArn: !GetAtt LambdaFunction.Arn
            AuthType: "NONE"
            Cors: 
                AllowCredentials: false
                AllowOrigins: 
                  - "*"

Outputs:
    LambdaUrl:
        Value: !Ref LambdaUrl
        Export:
            Name: "PlantShopAPI-LambdaUrl"
