AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""

Parameters:
    Subnet1:
        Type: "AWS::EC2::Subnet::Id"
        Description: "First subnet to deploy Lambda into"
    Subnet2:
        Type: "AWS::EC2::Subnet::Id"
        Description: "Second subnet to deploy Lambda into"
    SecurityGroup:
        Type: "AWS::EC2::SecurityGroup::Id"
        Description: "Security Group to deploy Lambda into"
    DatabaseEndpoint:
        Type: String
        Description: "Database endpoint to connect to"
    SourceCodeBucket:
        Type: String
        Description: "S3 bucket to store source code in"

Resources:
    LambdaRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                - Sid: AllowAssumeRole
                  Effect: Allow
                  # Using cloud_user (from AWS sandbox in ACG)
                  Principal:
                    AWS:
                        - !Join
                            - ""
                            - - "arn:aws:iam::"
                              - !Ref AWS::AccountId
                              - ":user/cloud_user"
                    Service:
                    - lambda.amazonaws.com
                  Action:
                  - sts:AssumeRole
            ManagedPolicyArns:
            - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
            - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
            - "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"

    LambdaFunction:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            Environment: 
                Variables: 
                    DB_PASS: "pl4nt5!"
                    DB_USER: "plantshop"
                    DB_HOST: !Ref DatabaseEndpoint
            FunctionName: "PlantShopAPI"
            Handler: "index.handler"
            Architectures: 
              - "x86_64"
            Code: 
                S3Bucket: !Ref SourceCodeBucket
                S3Key: "lambda.zip"
            MemorySize: 128
            Role: !GetAtt LambdaRole.Arn
            Runtime: "nodejs16.x"
            Timeout: 10
            TracingConfig: 
                Mode: "Active"
            VpcConfig: 
                SubnetIds:
                  - !Ref Subnet1
                  - !Ref Subnet2 
                SecurityGroupIds: 
                  - !Ref SecurityGroup
            EphemeralStorage: 
                Size: 512

    LambdaUrl:
        Type: "AWS::Lambda::Url"
        Properties:
            TargetFunctionArn: !GetAtt LambdaFunction.Arn
            AuthType: "NONE"
            Cors: 
                AllowCredentials: false
                AllowOrigins: 
                  - "*"

    PermissionForLambdaURLInvoke:
        Type: AWS::Lambda::Permission
        Properties:
            FunctionName: !Ref LambdaFunction
            FunctionUrlAuthType: 'NONE'
            Action: lambda:InvokeFunctionUrl
            Principal: '*'    
